mqtt:
  broker: tcp://server:1883
  preffix: rpi/
pir:
  pin: 35
  mqtt-suffix: pir
bme280:
  interval: 5m
  address: 0x76
ble:
  interval: 2m
  duration: 10s
  mqtt-preffix: location/
  known-devices:
    - aa:bb:cc:dd:aa:bb # bla
